### PR TITLE
Ensure valid delimiter.

### PR DESCRIPTION
**Pull request by jcs090218**
I am getting candidates with invalid delimiter. Ensure when certain delimiter.

### CODE REVIEW

**Comment by randomphrase** [comment]
Thanks but this should already be handled correctly - as you can see from the existing tests. Perhaps you can create/change the tests to exhibit the breakage you are seeing?

**Comment by jcs090218** [comment]
Hi, I have created a package called [company-fuzzy](https://github.com/jcs-elpa/company-fuzzy). I am trying to call to get a list of possible candidates by `company-fuzzy--call-backend`, this is almost the same as `(company-c-headers 'candidates "<")`. The issue is that I am getting candidates with incorrect prefix/delimiter infront, and the delimiter is the first character that I have pass in for prefix due to [L100](https://github.com/randomphrase/company-c-headers/blob/master/company-c-headers.el#L100). For instance, if I have passed in `stdi` for prefix then I am getting a list of candidates with character `s` infront! All candidates became something like `stdint.h` => `sstdint.h`, `iostream` => `siostream`, etc.

To keep something simple is this PR I am proposing, yet if you have a better idea; and please let me know! Thanks!

**Comment by jcs090218** [comment]
@randomphrase Any progress on this? Thanks!

The issue is described like the following screenshot.

Image 4

**Comment by randomphrase** [comment]
Hi, sorry I've been distracted due to personal issues, will try to look at this soon.

**Comment by jcs090218** [comment]
Any update on this?

**Comment by randomphrase** [comment]
Hey @jcs090218 are you still interested in merging this? Sorry for the extended delay in responding.

**Comment by randomphrase** [comment]
I guess the main question I have is, why is this change necessary? The delimiters should be correctly matched by the include regex at [L75](https://github.com/randomphrase/company-c-headers/blob/master/company-c-headers.el#L75) Sorry if I've missed something. FWIW, I don't really use this package myself any more.

**Pull request closed without merging**
